# Generated by Django 3.1.3 on 2020-11-17 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('post_title', models.CharField(max_length=63)),
                ('post_description', models.TextField()),
                ('post_attachment', models.FileField(null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('class_name', models.CharField(max_length=63)),
                ('section', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=63)),
                ('room', models.CharField(max_length=63)),
                ('class_code', models.CharField(max_length=15)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('class_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClassroomApi.classroom')),
                ('teacher_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('class_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClassroomApi.classroom')),
                ('student_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_invite_active', models.BooleanField(default=True)),
                ('student_can_post', models.BooleanField(default=True)),
                ('student_can_comment', models.BooleanField(default=True)),
                ('show_deleted_items', models.BooleanField(default=False)),
                ('class_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClassroomApi.classroom')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassPostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('post_comment', models.TextField()),
                ('class_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClassroomApi.classroom')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClassroomApi.classpost')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='classpost',
            name='class_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClassroomApi.classroom'),
        ),
        migrations.AddField(
            model_name='classpost',
            name='post_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
