# Generated by Django 3.1.3 on 2020-11-17 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClassroomApi', '0002_auto_20201117_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classpost',
            old_name='post_attachment',
            new_name='post_attachment_url',
        ),
    ]
