# Generated by Django 3.1.3 on 2020-11-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassroomApi', '0003_auto_20201117_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='meetUrl',
            field=models.URLField(null=True),
        ),
    ]
