# Generated by Django 3.1.3 on 2020-11-18 22:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ClassroomApi', '0004_classroom_meeturl'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classstudent',
            unique_together={('class_fk', 'student_fk')},
        ),
    ]
