# Generated by Django 3.1.3 on 2020-11-18 22:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ClassroomApi', '0005_auto_20201118_2257'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classteacher',
            unique_together={('class_fk', 'teacher_fk')},
        ),
    ]
