# Generated by Django 3.1.3 on 2020-11-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassroomApi', '0006_auto_20201118_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='meetUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
