# Generated by Django 3.1.3 on 2020-11-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassroomApi', '0007_auto_20201121_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_code',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
