# Generated by Django 3.1.3 on 2020-11-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassroomApi', '0008_auto_20201121_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classpost',
            name='post_attachment_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
