# Generated by Django 3.1.3 on 2020-11-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassroomApi', '0009_auto_20201121_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classpost',
            options={'ordering': ['-updated']},
        ),
        migrations.AlterField(
            model_name='classroom',
            name='class_code',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
